### ISSUE TITLE
Use python built-in type hinting for functions.

### ISSUE THREAD

**Issue by Nate1729** [RackReaver/Vulcan#23]
Currently type hinting is not used in the codebase, leading to code like this (from `avmp/utils/ip_tools.py`)

```
def get_all_network_ips(network):
    """Given a network (0.0.0.0/24) return all possible ip addresses
    arg:
        network (str): IP network to extract IP's from
    return (list): IP's in given network
    """
    return [str(ip) for ip in IPNetwork(network)]
```

The alternative would be to do something like this
```
def get_all_network_ips(network: str) -> List[str]:
    """Given a network (0.0.0.0/24) return all possible ip addresses
    arg:
        network: IP network to extract IP's from
    return: IP's in given network
    """
    return [str(ip) for ip in IPNetwork(network)]
```

1. Code is more readable
2. Allows for integration of static typing tools like mypy to help with CI/CD
3. There is nothing enforcing or even suggesting the use of a string for the `network` argument (currently) unless a user looks up this function. 
4. Easy transition to using python's dataclasses library
5. Remove the visual clutter of typing from the docstring

**Comment by RackReaver** [comment]
Looks good, feel free to implement it on ip_tools.py
